#define MAIS      1
#define MENOS     2 
#define MULT      3 
#define DIV       4 
#define NUM       5 
#define ID        6 
#define ATRIB     7
#define PV        8
#define ABREPAR   9 
#define FECHAPAR 10